### ISSUE TITLE
Support setting timeline on ProxyAnimation.

### ISSUE THREAD

**Issue by flackr** [flackr/scroll-timeline#15]
Setting the timeline requires custom logic in a set timeline method in proxy-animation.js in order to correctly switch to/from ScrollTimelines and perform the appropriate changes to the animation expected by [setting-timeline.tentative.html](https://github.com/web-platform-tests/wpt/blob/master/scroll-animations/setting-timeline.tentative.html).

The following tests currently fail with `Error: promise_test: Unhandled rejection with value: object "TypeError: Failed to set the 'timeline' property on 'Animation': Failed to convert value to 'AnimationTimeline'."`:

* Setting a scroll timeline on a play-pending animation synchronizes currentTime of the animation with the scroll position. 
* Setting a scroll timeline on a pause-pending animation fixes the currentTime of the animation based on the scroll position once resumed                                                                                                                             
* Setting a scroll timeline on a reversed play-pending animation synchronizes the currentTime of the animation with the scroll position.                                                                                                                              
* Setting a scroll timeline on a running animation synchronizes the currentTime of the animation with the scroll position. 
* Setting a scroll timeline on a paused animation fixes the currentTime of the animation based on the scroll position when resumed 
* Setting a scroll timeline on a reversed paused animation fixes the currentTime of the animation based on the scroll position when resumed                                                                                                                           
* Transitioning from a scroll timeline to a document timeline on a running animation preserves currentTime 
* Transitioning from a scroll timeline to a document timeline on a pause-pending animation preserves currentTime 
* Transitioning from a scroll timeline to a null timeline on a running animation preserves the play state 
* Switching from one scroll timeline to another updates currentTime 
* Switching from a document timeline to a scroll timeline updates currentTime when unpaused via CSS. 
* Switching from a document timeline to a scroll timeline and updating currentTime preserves the new value when unpaused. 
* Switching from a document timeline to a scroll timeline and updating startTime preserves the new value when play is called. 

And one test fails with `Error: promise_test: Unhandled rejection with value: object "TypeError: Cannot set property timeline of #<t> which has only a getter"`:
* Switching from a null timeline to a scroll timeline on an animation with a resolved start time preserved the play state

**Comment by bramus** [comment]
Fixed in #18 I believe.
