### ISSUE TITLE
CSSMathNegate and CSSMathInvert should have a read only value attribute

### ISSUE THREAD

**Issue by johannesodland** [flackr/scroll-timeline#169]
All CSSMathValues in the proxy-cssom have a readonly `values` attribute returning a CSSNumericArray, but [CSSMathNegate](https://www.w3.org/TR/css-typed-om-1/#cssmathnegate) and [CSSMathInvert](https://www.w3.org/TR/css-typed-om-1/#cssmathinvert) should have a singular `value` attribute [according to the spec](https://www.w3.org/TR/css-typed-om-1/#complex-numeric).

Code attempting to read the value attribute in browsers where proxy-cssom is used will fail.

This is not a full CSS Typed OM polyfill, but if we want to support using calculations in ranges, we need to be able to read the value attribute.

**Comment by bramus** [comment]
With #170 being merged, this issue may be closed now.
