### ISSUE TITLE
Safari support

### ISSUE THREAD

**Issue by tzappia** [flackr/scroll-timeline#21]
This polyfill is really cool! It makes use of the CSS Typed Object Model with CSSUnitValue, CSSKeywordValue, and CSSMathSum, none of which Safari supports. Do you think it's worth forking this and working on a version that accounts for this, or am I likely to run into other blockers?

**Comment by flackr** [comment]
The polyfill actually used to not require these types, but in order to properly pass the web platform tests we migrated to using them. I think we can implement mini polyfills of the missing CSS typed OM types to address those gaps and get cross browser interop. This is one of the things I'm hoping we can address soon.

**Comment by tzappia** [comment]
Awesome, glad to hear! I integrated [this polyfill](https://github.com/csstools/css-typed-om) into your demo page and all but the panorama demo seemed to work as expected.

**Comment by bramus** [comment]
Here's the default polyfill loading code I use in [all my ScrollTimeline experiments](https://codepen.io/collection/DkdaQK). It uses both `css-typed-om` polyfill and the `scroll-timeline` polyfill.

```js
import polyfill from "https://cdn.skypack.dev/css-typed-om";

// Stuff that needs to be done first
const bootstrap = async () => {
	
	// Load CSSKeywordValue Polyfill
	// @note: Script already imported (see import above), only needs to be attached to window
	if (typeof CSSKeywordValue == "undefined") {
		polyfill(window);
	}
	
	// Load ScrollTimeline
	// @note: This polyfill contains an IIFE, so we only need to load it.
	if (typeof ScrollTimeline == "undefined") {
		const polyfill = () => new Promise((resolve, reject) => {
			const script = document.createElement("script");
			script.async = true;
			script.src =
				"https://flackr.github.io/scroll-timeline/dist/scroll-timeline.js";
			script.onload = resolve;
			script.onerror = reject;
			document.head.appendChild(script);
		});
		
		await polyfill().catch(e => false);
	}

	// Make sure we have everything
	if (
		typeof Animation == "undefined" ||
		typeof CSSKeywordValue == "undefined" ||
		typeof KeyframeEffect == "undefined" ||
		typeof ScrollTimeline == "undefined"
	) {
		return false;
	}
	
	return true;
}

// Bootstrap first, and then execute
const go = async () => {
	const bootstrapped = await bootstrap();
	
	if (!bootstrapped) {
		document.querySelector(".warning").style.display = "block";
		return;
	}

	// 👉 YOUR SCROLL-TIMELINE ANIMATION CODE HERE 👈
}

// Thunderbirds are go!
go();
```

_(Due to #4 I have to load the `scroll-timeline` polyfill in a somewhat clunky way …)_

**Comment by tzappia** [comment]
@bramus awesome, thanks!

**Comment by bramus** [comment]
Now that #33 has been merged, this issue may be closed :)

The loading logic as mentioned [above](https://github.com/flackr/scroll-timeline/issues/21#issuecomment-774053679) can now be adjusted to no longer load `https://cdn.skypack.dev/css-typed-om`.

See https://codepen.io/bramus/pen/PobZbBV for a working / adjusted example.

**Comment by flackr** [comment]
Thanks for testing and confirming!
