### ISSUE TITLE
Animate z-index of an element with element animate() method

### ISSUE THREAD

**Issue by WEBSosman** [flackr/scroll-timeline#282]
On a web page, I have an element I would like to animate its z-index.

Here is my code:

```
myElement.animate({
    opacity: [0.1, 1.0, 0.1, 0],
    background: ["red", "green", "red"],
    z-index: [0, 128, 0]
}, {
    fill: 'forwards',
    timeline: new ViewTimeline({
        subject: animationTrigger

    }),
    rangeStart: {rangeName: 'entry', offset: CSS.percent(4)},
    rangeEnd: {rangeName: 'exit', offset: CSS.percent(64)},
});
```

I have tried z-index, zindex, but nothing works.

Apparently, I am using the wrong parameter for z-index. What is the correct parameter?

**Comment by bramus** [comment]
You have to use `zIndex`.

Closing, as this is not a scroll-timeline issue, but a generic WAAPI question.
