### ISSUE TITLE
Add unit/integration tests

### ISSUE THREAD

**Issue by majido** [flackr/scroll-timeline#3]
Currently the polyfill does not have any tests.

I suggest we look into adding test and setting up a CI pipeline to check new commits against those tests.

## Tests

Should be fairly easy to add some basic tests around timeline time calculations and animations correctly running.

One idea is to import/adapt the [wpt tests](https://cs.chromium.org/chromium/src/third_party/blink/web_tests/external/wpt/scroll-animations) for ScrollTimeline and run them against the polyfill. I haven't fully thought this through but it seems possible albeit may require us to change tests in a way that we can't easily keep syncing them.

## Test harness and CI
Key requirement here is to be able to test against all mainstream browsers.

In the [past](https://github.com/majido/high-resolution-timestamp-polyfill/blob/master/karma.conf.js) I have had success using **Karma** testing framework in conjunction with **Sauce Labs** to run tests against multiple browsers. But this was some times ago and there may be better solutions now.

**Comment by majido** [comment]
About the idea of reusing WPT idea. @flackr  pointed out that [web-animations-js polyfill](https://github.com/web-animations/web-animations-js/) is doing something like this.

The tricky bit is that we need to load the polyfill before the test runs. AFAICT, they are using Karma and [configure](https://github.com/web-animations/web-animations-js/blob/dev/test/karma-config.js#L18) that to load their [own special testharnessreport.js](https://github.com/web-animations/web-animations-js/blob/dev/test/resources/testharnessreport.js#L416
) that injects the polyfill using document.write() . This works because every wpt test loads testharnessreport.js at the top of the test.

Note that to use the above technique, there may be a need to change the polyfill so that it can be loaded synchronously though. From @flackr :

> One other point of contention is that the scroll-timeline polyfill right now loads as a module (read: asynchronously). I'm not attached to this - it seems as though it would be more useful to load synchronously into the main context to make it easier to load prior to running tests.

**Comment by flackr** [comment]
@zouhir Is this complete now?

**Comment by zouhir** [comment]
Yes, having I recall we agreed in a past Slack conversation that local unit-tests are redundant given we run WPT. Do you still think so?

**Comment by flackr** [comment]
Yes, I think so! Thanks again for all your work here.

We can close the dependent testing bugs too right?

**Comment by zouhir** [comment]
Yep!
