### ISSUE TITLE
Uncaught ReferenceError: proxy is not defined

### ISSUE THREAD

**Issue by bramus** [flackr/scroll-timeline#39]
The [most recent commit](https://github.com/flackr/scroll-timeline/commit/254a69ccf0153a6116430ee803b32ddc7a63476a) seems to break things in Chrome:

<img width="514" alt="Screenshot 2021-11-04 at 15 42 41" src="https://user-images.githubusercontent.com/213073/140335046-0ba0b089-dcb8-4b2f-adfa-8add02008ddc.png">

The version before this commit (i.e. https://rawcdn.githack.com/flackr/scroll-timeline/9c04dfcd4a9038f3659cae7af0d95c98e7bd17b6/dist/scroll-timeline.js) does not have this issue.

**Comment by kevers-google** [comment]
Investigating.

**Comment by bramus** [comment]
Didn't have time myself to investigate, so thanks for this very fast intervention.
