### ISSUE TITLE
NPM support

### ISSUE THREAD

**Issue by souporserious** [flackr/scroll-timeline#57]
First, thank you for such a great polyfill! The performance is much smoother than traditional scroll events. I was curious if this package will be available on NPM? I noticed `scroll-timeline-polyfill` doesn't exist in the registry, but it looks like everything is set up for this to work. I'm currently wanting to play with this polyfill in a React Codesandbox which uses create react app and doesn't seem to currently support URL imports. I was able to copy the dist file, but was curious if an NPM package will be supported to make things a little easier in these situations.

**Comment by okyanusoz** [comment]
If you need help, I can publish the package.

**Comment by Azarattum** [comment]
It would be nice if somebody were to publish and maintain this package.

**Comment by curtgrimes** [comment]
Telling npm/yarn/pnpm to install from GitHub could also be an option if importing the src/index.js file works directly (I was able to install, but did not try going further because I realized this polyfill won't work for my use case):

```
pnpm i -D github:flackr/scroll-timeline
# or: 
pnpm i -D github:flackr/scroll-timeline#b3d05a5
```

**Comment by dy** [comment]
@flackr any reason this is not published to npm?

**Comment by calinoracation** [comment]
I started looking at this a bit and pulled in the package by SHA to start with. Since there's no bundled `dist/` folder in the repo now, that doesn't work incredibly well. I also needed to change the `microbundle` in the `build` script to not use `-f` to produce more formats, specifically my bundler was only happy using the `dist/scroll-timeline-polyfill.modern.js` output. 

If it were being published, it might make sense to move that to the `browser` field in `package.json` and make those changes to include `dist/` by default in the published tarball.

**Comment by flackr** [comment]
I also have started looking into getting this set up. The rough plan is in PR https://github.com/flackr/scroll-timeline/pull/224#issuecomment-1925439103 with the build switch to vite. I think I should be able to set up a github action to publish releases to npm automatically following https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

**Comment by calinoracation** [comment]
Not sure if it's valuable but I've started testing publishing in a for-internal fork prior to the publishing y'all are going to do. I added some initial support to publish types with the package and a ES / CJS build.

**Comment by souporserious** [comment]
Just noticed this library has been [published to NPM](https://www.npmjs.com/package/scroll-timeline-polyfill) 🎉 thank you @flackr!

**Comment by ADTC** [comment]
_Comments moved to:_
* #296

**Comment by ADTC** [comment]
Also I'm extremely confused how to enable this polyfill after importing it as an NPM package? It doesn't just start working immediately, and I can't figure out any import statements.

I tried this:

```html
    <script>
      import 'scroll-timeline-polyfill'
    </script>
```

But getting error:

```
[commonjs--resolver] Failed to resolve entry for package "scroll-timeline-polyfill". 
The package may have incorrect main/module/exports specified in its package.json.
```

I'm only using CSS based scroll-timeline (view timeline actually), if that matters.

@souporserious @flackr
