### ISSUE TITLE
ViewTimeline phases for elements that are larger than the scrollport wrong

### ISSUE THREAD

**Issue by bramus** [flackr/scroll-timeline#62]
See demo at https://codepen.io/bramus/pen/VwXMRrW?editors=0010 where I animate the `#sticky-parallax-header` element by looking at the `#content` element during the `enter` phase.

As you scroll down, the header does animate but too slowly because the `enter` phase is wrongly determined. As per [breakout session in June](https://lists.w3.org/Archives/Public/www-style/2022Jun/0013.html) the phases for elements larger than the scrollport look like this:

<img width="455" alt="image" src="https://user-images.githubusercontent.com/213073/181842161-6b6093cb-746e-4925-9fc2-45b44d4f36aa.png">

**Comment by kevers-google** [comment]
Fixed
