### ISSUE TITLE
Is the public script up to date?

### ISSUE THREAD

**Issue by adaptifyDesigns** [flackr/scroll-timeline#63]
@flackr @bramus  @kevers-google 
Hello, I've been using this polyfill on a production site for several months. Recently the `scrollOffsets` properties (as defined in the `ScrollTimeline` class) stopped functioning as they did when I originally configured the animations... I checked here and saw there had been some updates relating to this, although I admit I do not understand them very well...

On the demo page I noticed that all the `ScrollTimeline` classes had been replaced by `ViewTimeline`:

```
timeline: new ViewTimeline({ subject: container }),
timeRange: 'contain 20% 80%' 
```

So I tried updating my animations accordingly, but the animations completely break, without any console errors. 

I'm using the script referenced in the readme: https://flackr.github.io/scroll-timeline/dist/scroll-timeline.js

Is the above script up to date? How can I get my animations back on track. Thanks!

This is what I currently have for one of my animations:

```
element.animate(
  [
    { clipPath: 'inset(0% 60% 0% 0%)' },
    { clipPath: 'inset(0% 0% 0% 0%)', offset: 0.46 },
    { clipPath: 'inset(0% 0% 0% 0%)', offset: 0.46 },
    { clipPath: 'inset(0% 60% 0% 0%)' }
  ],
  {
    duration: 1,
    easing: 'cubic-bezier(0,.44,1,.57)',
    fill: "both",
    timeline: new ScrollTimeline({
        scrollSource: document.documentElement,
        scrollOffsets: [
          { target: element, edge: 'end', threshold: 0 },
          { target: element, edge: 'start', threshold: 0 }
        ],
        fill: 'both',
    }),
  }
);
```

The goal is to have the above keyframes start as the top of the element first comes into the bottom of the viewport, and end as the bottom of the element leaves the top of the viewport. This was working as expected up until recently. Last time I checked it is not. And I'm not sure what exactly it's doing... The animation seems to start before the element comes into the viewport, and it barely gets halfway through before the element has left the viewport. Perhaps the animation timeline is based on the entire document scroll...?

Any suggestions would be so much appreciated. It's very difficult to find support for this on the web. I'm not sure who to ask besides you. Thanks so much!

**Comment by adaptifyDesigns** [comment]
I've been playing with various versions of `scrollOffsets` and I can't get anything to work. The animation timeline seems to be unchanged, no matter how I change my configuration. I think the animations are being timed based on the total length of the page it's on. I can't seem to get the animations to be bound by specific scroll offsets. 

Please help!

**Comment by bramus** [comment]
Yes, the script tries to stay up-to-date with _([the rewrite of](https://drafts.csswg.org/scroll-animations-1/rewrite))_ the spec. `scroll-offsets` have been removed from the spec. See https://github.com/flackr/scroll-timeline/issues/64 for a more extensive answer.
