### ISSUE TITLE
Uncaught TypeError: Failed to execute 'updateTiming' on 'AnimationEffect': duration must be non-negative or auto

### ISSUE THREAD

**Issue by bramus** [flackr/scroll-timeline#73]
In https://codepen.io/bramus/pen/WNzZmdP I am trying to animate a horizontal strip `.pin-wrap` while its parent `#sectionPin` is in the `contain` phase.

It should behave like https://codepen.io/bramus/pen/MWVvrEE, but instead I am getting this error in the Console:

> Uncaught TypeError: Failed to execute 'updateTiming' on 'AnimationEffect': duration must be non-negative or auto
>     at Object.apply (proxy-animation.js:708:30)
>     at proxy-animation.js:105:39
>     at V (proxy-animation.js:370:18)
>     at N (proxy-animation.js:91:24)
>     at _ (proxy-animation.js:262:24)
>     at e.get (proxy-animation.js:1094:36)
>     at e.get (proxy-animation.js:1172:56)
>     at H (proxy-animation.js:447:20)
>     at n.play (proxy-animation.js:1306:5)
>     at HTMLDivElement.value [as animate] (proxy-animation.js:1721:20)

Note that the parent is taller than the viewport, which [might have to do with this](https://github.com/flackr/scroll-timeline/issues/62).

**Comment by kevers-google** [comment]
Fixed.  Contain bounds should be reversed if exiting before fully entered.  Failure to do so resulted in a negative duration being calculated.
