### ISSUE TITLE
Console Errors

### ISSUE THREAD

**Issue by ericwfisher** [flackr/scroll-timeline#93]
The demo projects seem to run fine but when I copy the dist files to my existing application (it's a large angular 14 app, hence tons of style tags in the header ... if that's helpful to know) and link to `scroll-timeline.js`, I get the errors (pasted below) thrown upon initial load, before I have even attempted to implement any sort of scroll based animations. 

Of note: The polyfill does seem to succeed and it turns out I can programmatically create animations via `ScrollTimeline`.

```
scroll-timeline-css-parser.js:630 Uncaught TypeError: this.parseError is not a function
    at n.advance (scroll-timeline-css-parser.js:630:18)
    at n.eatUntil (scroll-timeline-css-parser.js:637:12)
    at n.parseSelector (scroll-timeline-css-parser.js:650:10)
    at n.parseQualifiedRule (scroll-timeline-css-parser.js:562:27)
    at n.transpileStyleSheet (scroll-timeline-css-parser.js:79:27)
    at e (scroll-timeline-css.js:39:25)
    at MutationObserver.observe.childList (scroll-timeline-css.js:13:11)
```

```
scroll-timeline-css.js:70 Uncaught TypeError: Cannot read properties of null (reading 'animation-timeline')
    at scroll-timeline-css.js:70:24
    at scroll-timeline-css.js:162:24
    at Array.forEach (<anonymous>)
    at scroll-timeline-css.js:153:89
```

**Comment by mehdi-kazemi** [comment]
Thanks for reporting this. 
You get this error after opening demo files? Which demo file?

**Comment by ericwfisher** [comment]
Not the demo files. Those run fine. It's when I try to integrate into my own larger application.

**Comment by mehdi-kazemi** [comment]
That could be the case. If you can share some of your examples, I can take a look into them.

**Comment by ericwfisher** [comment]
I'll see what I can do. I don't have a lot of time to dedicate to this and I can't publicly expose the app itself. I'll try to create a shareable example that reproduces the issue, but it may take some time. Bear with me.

**Comment by ericwfisher** [comment]
Okay, I figured out how to reproduce the error. Something in my css processing chain is appending `@charset "UTF-8"` to the end of a style block which in turn causes the error in css parser. You can reproduce this in any demo by adding `@charset "UTF-8"` as the final line (or the only line) of any style block. As long as it is not the final line the parser seems to handle it gracefully.

**Comment by bramus** [comment]
This is invalid use. `@charset` **must** be first in the style sheet and not be preceded by any character. See [the spec](https://w3c.github.io/csswg-drafts/css2/#charset%E2%91%A0) for more details.

**Comment by ericwfisher** [comment]
I am aware that it is invalid. I didn't think that fact was relevant to the parser throwing an error.

**Comment by carletonm** [comment]
I'm getting the exact same error while trying to use the polyfill on my Wordpress website.

Uncaught TypeError: this.parseError is not a function
    at n.advance (scroll-timeline-css-parser.js:681:18)
    at n.eatUntil (scroll-timeline-css-parser.js:688:12)
    at n.parseSelector (scroll-timeline-css-parser.js:701:10)
    at n.parseQualifiedRule (scroll-timeline-css-parser.js:612:27)
    at n.transpileStyleSheet (scroll-timeline-css-parser.js:81:27)
    at e (scroll-timeline-css.js:39:25)
    at MutationObserver.observe.childList (scroll-timeline-css.js:13:11)

**Comment by NikolaCurcic94** [comment]
Access to script at '.....' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, isolated-app, chrome-extension, chrome, https, chrome-untrusted.

Hello, can anyone help me with this? I'm trying to use polyfill and this appeared

**Comment by bramus** [comment]
I dug a bit deeper and noticed that `parseError` was simply missing from the polyfill. I added this back in https://github.com/flackr/scroll-timeline/pull/139. This issue can be closed, as the error no longer appears (ping @kevers-google @flackr).

As for the polyfill not being able to parse `@charset` and other at-rules: that’s being tracked in #80 and #100.
